{
 "title": "Plasma Node Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "quantile", "query": "0.99,0.95,0.9,0.5" },
   { "name": "block_gas_limit", "query": "36000000" },
   { "name": "direction", "query": "inbound,outbound" },
   { "name": "message_kind", "query": "block,vote,new_view" }
  ]
 },
 "panels": [
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Docker Images",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(image) (container_last_seen{name=~\"(plasma-execution|plasma-consensus)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Consensus Uptime",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(instance) (up{instance=\"plasma-consensus:9001\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Reth Uptime",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max by(instance) (up{instance=\"plasma-execution:9001\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Chain progression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Canonical Chain Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by(instance) (reth_blockchain_tree_canonical_chain_height)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Blocks per per second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Block / s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(instance) (rate(reth_blockchain_tree_canonical_chain_height[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Reorg(s) / s" } },
   "targets": [
    {
     "expr": "max by(instance) (rate(reth_blockchain_tree_reorgs[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPC health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "New Payload latency",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max by(instance, quantile) (reth_engine_rpc_new_payload_v4{quantile=~\"$quantile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Get Payload latency",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "max by(instance, quantile) (reth_engine_rpc_get_payload_v4{quantile=~\"$quantile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Reth Connection health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Reth Connected Peers",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "max by(instance) (reth_network_connected_peers)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reth pending failed sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Session(s) / s" } },
   "targets": [
    {
     "expr": "max by(instance) (rate(reth_network_pending_session_failures[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reth closed sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Session(s) / s" } },
   "targets": [
    {
     "expr": "max by(instance) (rate(reth_network_closed_sessions[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reth messages dropped (backpressure)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Msg(s) / s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(reth_network_total_outgoing_peer_messages_dropped[$__rate_interval])) + (sum by(instance) (rate(reth_network_egress_peer_channel_full[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reth network ping timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(instance) (rate(reth_network_ping_timeout[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reth invalid + unsolicited messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Msg(s) / s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(reth_network_invalid_messages_received[$__rate_interval])) + (sum by(instance) (rate(reth_network_unsolicited_transactions[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Propagated Transactions Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Tx(s) / s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(reth_network_propagated_transactions[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Consensus Connection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Consensus Active Connections",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "max by(instance) (plasma_networking_connections_active{direction=~\"$direction\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Active Streams",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "max by(instance) (plasma_networking_synchronization_active_streams)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Synchronization Streams (avg over time)",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "max by(instance) (avg_over_time(rate(plasma_networking_synchronization_streams_total[$__rate_interval])[1h:$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Connections Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "errors/s" } },
   "targets": [
    {
     "expr": "max by(instance) (rate(plasma_networking_connections_attempt_errors_total{direction=~\"$direction\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Connection Duration (avg over time)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(plasma_networking_connections_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Message Rate ($message_kind)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "max by(instance) (rate(plasma_networking_messages_total{direction=~\"$direction\", kind=~\"$message_kind\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Sync Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "max by(instance) (rate(plasma_networking_synchronization_in_stream_errors_total[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Execution throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Block execution time",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "max by(instance, quantile) (reth_sync_execution_execution_histogram{quantile=~\"$quantile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile($quantile, max by(instance) (reth_engine_rpc_new_payload_total_gas)) / {\"$block_gas_limit\"}",
     "legendFormat": "Block Utilization % q90"
    }
   ]
  },
  { "title": "Pool contents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Total transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "Tx(s)" } },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_total_transactions)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tx Pool Pending Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_pending_pool_size_bytes)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Peding Txs (Waiting for block)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "Tx(s)" } },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_pending_pool_transactions)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Invalid Tx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "Tx(s) / s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(reth_transaction_pool_invalid_transactions[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "(Underpriced) Base Fee Txs (Waiting for lower prices)",
   "type": "timeseries",
   "description": "Invalid because they've set their base fee too low.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "Tx(s)" } },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_basefee_pool_transactions)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tx removal rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "Tx(s) / s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(reth_transaction_pool_removed_transactions[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Currently invalid Txs (eg Waiting for nonce/funds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "Tx(s)" } },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_queued_pool_transactions)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Pool Legacy Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_total_legacy_transactions)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transaction Pool eip1559 Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_total_eip1559_transactions)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transaction Pool eip2930 Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_total_eip2930_transactions)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transaction Pool eip4844 Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_total_eip4844_transactions)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Pool eip7702 Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "targets": [
    {
     "expr": "max by(instance) (reth_transaction_pool_total_eip7702_transactions)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Consensus - Resources Used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Consensus Volume Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_fs_usage_bytes{name=\"plasma-consensus\"} * 100) / container_fs_limit_bytes{name=\"plasma-consensus\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Volume Hourly Growth Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(name) (increase(container_fs_usage_bytes{name=\"plasma-consensus\"}[1h]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Plasma Consensus Working Set Memory",
   "type": "timeseries",
   "description": "Just memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(name) (label_replace(container_memory_working_set_bytes{name=\"plasma-consensus\"}, \"instance\", \"$1\", \"namespace\", \"$extract_short_name\"))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Plasma Consensus Total Memory",
   "type": "timeseries",
   "description": "Includes file caching",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(name) (container_memory_usage_bytes{name=\"plasma-consensus\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Plasma Consensus CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 180 },
   "targets": [
    {
     "expr": "sum by(name) (irate(container_cpu_usage_seconds_total{name=\"plasma-consensus\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth (Consensus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(image) (rate(container_network_receive_bytes_total{image=~\".*plasma-consensus.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth (Consensus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(image) (rate(container_network_transmit_bytes_total{image=~\".*plasma-consensus.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Packets per Second (Consensus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(image) (rate(container_network_receive_packets_total{image=~\".*plasma-consensus.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted Packets per Second (Consensus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(image) (rate(container_network_transmit_packets_total{image=~\".*plasma-consensus.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Execution - Resources Used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 } },
  {
   "title": "Reth Volume Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_fs_usage_bytes{name=\"plasma-execution\"} * 100) / container_fs_limit_bytes{name=\"plasma-execution\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reth Volume Hourly Growth Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(name) (increase(container_fs_usage_bytes{name=\"plasma-execution\"}[1h]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Reth Consensus Working Set Memory",
   "type": "timeseries",
   "description": "Just memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(name) (label_replace(container_memory_working_set_bytes{name=\"plasma-execution\"}, \"instance\", \"$1\", \"namespace\", \"$extract_short_name\"))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Reth Consensus Total Memory",
   "type": "timeseries",
   "description": "Includes file caching",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(name) (container_memory_usage_bytes{name=\"plasma-execution\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Reth Consensus CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "sum by(name) (irate(container_cpu_usage_seconds_total{name=\"plasma-execution\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth (Reth)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(image) (rate(container_network_receive_bytes_total{image=~\".*reth.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth (Reth)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(image) (rate(container_network_transmit_bytes_total{image=~\".*reth.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Packets per Second (Reth)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(image) (rate(container_network_receive_packets_total{image=~\".*reth.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted Packets per Second (Reth)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(image) (rate(container_network_transmit_packets_total{image=~\".*reth.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}